export const categories = [
  "Accounting",
  "Agri Tech",
  "AI",
  "Animals",
  "Architecture",
  "Art",
  "Automotive",
  "Banking",
  "Beauty",
  "Beverages",
  "Books",
  "Business",
  "Career",
  "Cloud Computing",
  "Coding",
  "Community",
  "Cooking",
  "Creative Writing",
  "Cryptocurrency",
  "Culture",
  "Data Science",
  "Design",
  "Digital Marketing",
  "DIY",
  "E-Commerce",
  "Education",
  "Environment",
  "Entrepreneurship",
  "Entertainment",
  "Events",
  "Fashion",
  "Finance",
  "Fitness",
  "Food",
  "Food Recipes",
  "Gaming",
  "Garden",
  "Green Tech",
  "Health",
  "History",
  "Home Decor",
  "Home Gardening",
  "Human Resources",
  "Insurance",
  "Investment",
  "IoT",
  "JavaScript",
  "Journalism",
  "Law",
  "Leadership",
  "Lifestyle",
  "Literature",
  "Machine Learning",
  "Marketing",
  "Mathematics",
  "Mental Health",
  "Minimalism",
  "Mobile Apps",
  "Music",
  "Nature",
  "News",
  "Nutrition",
  "Open Source",
  "Outdoors",
  "Parenting",
  "Personal Development",
  "Photography",
  "Politics",
  "Podcasting",
  "Productivity",
  "Programming",
  "Real Estate",
  "Relationships",
  "Remote Work",
  "Research",
  "Robotics",
  "Science",
  "Self Improvement",
  "Sewing",
  "Small Business",
  "Social Media",
  "Space",
  "Sports",
  "Startups",
  "Storytelling",
  "Sustainability",
  "Technology",
  "Tech Reviews",
  "Travel",
  "UI/UX",
  "Urban Living",
  "UX Research",
  "Values",
  "Video Games",
  "Virtual Reality",
  "Wellness",
  "Web Development",
  "Writing",
  "Yoga",
  "Zoology",
].sort((a, b) => a.localeCompare(b));
