FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    sqlite3 \
    libsqlite3-dev \
    libpq-dev \
    && docker-php-ext-install pdo pdo_sqlite pdo_pgsql \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

RUN touch database/database.sqlite

RUN php artisan config:clear
RUN php artisan migrate --force

EXPOSE 10000

CMD ["sh","-c","php artisan serve --host=0.0.0.0 --port=${PORT:-10000}"]
